import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import HeaderOne from '@/components/HeaderOne'
import HeaderMain from '@/components/HeaderMain'
import NavBar from '@/components/NavBar'
import MobileNav from '@/components/MobileNav'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HeaderOne />
        <HeaderMain />
        <NavBar />
        <MobileNav />
        {children}
        <Footer />
      </body>
    </html>
  )
}
